In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.3.0


* Creating variable objects of different types

In [3]:
strings = tf.Variable(["Hello world"], tf.string)

floats = tf.Variable([3.14375, 2.78732], tf.float64)

ints = tf.Variable([1, 2, 3], tf.int32)

complexes = tf.Variable([25.9 - 7.39j, 1.23 - 4.91j], tf.complex128)

In [4]:
tf.Variable(tf.constant(4.2, shape=(3,3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]], dtype=float32)>

In [5]:
v = tf.Variable(0.0)

w = v + 1

print(type(w))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
v.assign_add(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [7]:
v.assign_sub(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


### Creating tensor objects

In [8]:
x = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print("dtype:", x.dtype)
print("shape:", x.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [9]:
# Obtaining the value as a numpy array

x.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Creating coefficients


* Initialising shapes


* Creating tensors of different shapes

In [10]:
coeffs = np.arange(16)

In [11]:
shape1 = [8,2]
shape2 = [4,4]
shape3 = [2, 2, 2, 2]

In [12]:
a = tf.constant(coeffs, shape=shape1)
print("\n a:\n ", a)

b = tf.constant(coeffs, shape=shape2)
print("\n b:\n ", b)

c = tf.constant(coeffs, shape=shape3)
print("\n c:\n ", c)


 a:
  tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int32)

 b:
  tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)

 c:
  tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int32)


* Creating a ones and a zeros Tensor


* Concatenating the two tensors

In [13]:
t1 = tf.ones(shape=(2, 2))
t2 = tf.zeros(shape=(2, 2))

In [14]:
concat0 = tf.concat([t1, t2], 0)
concat1 = tf.concat([t1, t2], 1)

In [15]:
print(concat0)
print(concat1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]], shape=(2, 4), dtype=float32)
